"use client";

import { FormEvent, useState } from "react";
import {
  ArrowRight, BarChart3, Building2, CalendarCheck, CheckCircle2,
  Headphones, Languages, Menu, PhoneCall, ShieldCheck, Sparkles,
  Stethoscope, Wrench, X,
} from "lucide-react";

const problems = [
  [PhoneCall, "Missed leads", "When calls go unanswered, new business goes elsewhere."],
  [Headphones, "Long hold times", "Customers should not have to wait to be heard."],
  [CalendarCheck, "After hours", "Your business should be present beyond business hours."],
  [BarChart3, "Lost revenue", "Every dropped conversation is a missed opportunity."],
];
const features = [[PhoneCall, "24/7 answering"], [CalendarCheck, "Appointment booking"], [ShieldCheck, "Lead qualification"], [ArrowRight, "Call transfers"], [Languages, "Bilingual support"], [BarChart3, "Analytics dashboard"], [Headphones, "Conversation history"], [Sparkles, "Call recording"], [Building2, "Custom voice agents"]];
const industries = [[Building2, "Property Management"], [Wrench, "HVAC"], [Stethoscope, "Dental"], [Headphones, "Veterinary"], [ShieldCheck, "Insurance"], [Building2, "Storage"], [ShieldCheck, "Law Firms"], [Stethoscope, "Medical Clinics"], [Wrench, "Home Services"], [Building2, "Automotive"]];
const faq = [["How human does the voice agent sound?", "Natural, clear, and tailored to your business. The goal is a reliable first response that feels helpful from the first word."], ["Can calls be transferred?", "Yes. When a customer needs a person, Portico routes the call with context so the handoff feels seamless."], ["Can I customize the agent?", "Yes. Your agent can be trained on your services, hours, policies, routing rules, and preferred conversation style."], ["Do you support English and French?", "Yes. Portico supports bilingual customer experiences in English and French."], ["How long does setup take?", "Self-serve customers can get started quickly. Enterprise onboarding is scoped around your workflow and integrations."], ["What happens if the agent cannot solve the request?", "The call is warm-transferred to a real person for help."]];

function ProductPreview() {
  return <div className="product">
    <div className="app"><aside className="sidebar"><b className="wordmark">PORTICO</b><p className="side-title">WORKSPACE</p>{["Overview", "Calls", "Appointments", "Conversations", "Analytics"].map((item, i) => <div key={item} className={`side-item ${i === 0 ? "active" : ""}`}>{item}</div>)}</aside>
      <main className="appmain"><div className="apphead"><div><h3>Good morning, Portico</h3><span className="fine">Monday, July 20</span></div><span className="status">● All systems live</span></div>
        <div className="stats">{[["Today’s calls", "48"], ["Appointments", "12"], ["Transfers", "6"], ["Avg. response", "1.2s"]].map(([label, value]) => <div className="stat" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>
        <div className="appgrid"><div className="panel"><h4>Recent conversations</h4>{["New patient inquiry", "Service appointment", "After-hours support"].map((item, i) => <div className="call" key={item}><span><b>{item}</b><br /><small>Sample call · {i + 2} min ago</small></span><span className="tag">Handled</span></div>)}</div><div className="panel"><h4>Current call</h4><b className="call-name">Incoming customer</b><p className="fine">Transcript preview</p><div className="wave">{Array.from({ length: 20 }, (_, i) => <i key={i} />)}</div><span className="tag">Voice agent active</span></div></div>
      </main></div>
  </div>;
}

function ContactModal({ mode, onClose }: { mode: "trial" | "demo"; onClose: () => void }) {
  const [sent, setSent] = useState(false);
  const isTrial = mode === "trial";
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSent(true); }
  return <div className="modal-backdrop" role="presentation" onMouseDown={onClose}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="contact-title" onMouseDown={e => e.stopPropagation()}>
    <button className="modal-close" aria-label="Close form" onClick={onClose}><X size={20} /></button>
    {sent ? <div className="success"><CheckCircle2 size={38} /><h2>You’re all set.</h2><p>Thanks for your interest. We’ll be in touch shortly.</p><button className="button primary" onClick={onClose}>Close</button></div> : <><span className="eyebrow">{isTrial ? "Start free" : "Let’s talk"}</span><h2 id="contact-title">{isTrial ? "Start your 14-day trial." : "Book an enterprise demo."}</h2><p>{isTrial ? "Tell us where to send your trial details." : "Share a few details and our team will tailor the conversation to your operation."}</p><form onSubmit={submit}><label>Work email<input required type="email" name="email" placeholder="you@company.com" /></label><label>Company name<input required name="company" placeholder="Your company" /></label>{!isTrial && <label>Team size<select name="teamSize" defaultValue=""><option value="" disabled>Select a range</option><option>1–10</option><option>11–50</option><option>51–250</option><option>251+</option></select></label>}<button className="button primary" type="submit">{isTrial ? "Request trial" : "Request demo"}<ArrowRight size={16} /></button></form></>}
  </section></div>;
}

export function LandingPage() {
  const [mobileOpen, setMobileOpen] = useState(false);
  const [modal, setModal] = useState<"trial" | "demo" | null>(null);
  const open = (mode: "trial" | "demo") => { setMobileOpen(false); setModal(mode); };
  const links = [["#solution", "Solutions"], ["#industries", "Industries"], ["#enterprise", "Enterprise"], ["#pricing", "Pricing"]];
  return <><div id="top" className="shell"><nav className="nav" aria-label="Main navigation"><a className="wordmark" href="#top">PORTICO</a><div className="navlinks">{links.map(([href, label]) => <a href={href} key={label}>{label}</a>)}</div><div className="nav-actions"><button className="button secondary" onClick={() => open("demo")}>Book Demo</button><button className="button primary" onClick={() => open("trial")}>Start Free Trial</button></div><button className="menu-button" aria-label="Toggle menu" aria-expanded={mobileOpen} onClick={() => setMobileOpen(!mobileOpen)}>{mobileOpen ? <X /> : <Menu />}</button></nav>{mobileOpen && <div className="mobile-menu">{links.map(([href, label]) => <a href={href} key={label} onClick={() => setMobileOpen(false)}>{label}</a>)}<button className="button primary" onClick={() => open("trial")}>Start Free Trial</button></div>}</div>
    <main><section className="hero"><div className="shell"><span className="eyebrow">Hybrid call center</span><h1>Every Call Answered.<br />Every Time.</h1><p>Voice agents answer instantly. Real people step in when needed. Never let another customer reach voicemail.</p><div className="hero-actions"><button className="button primary" onClick={() => open("trial")}>Start Free Trial <ArrowRight size={16} /></button><button className="button secondary" onClick={() => open("demo")}>Book Enterprise Demo</button></div><div className="fine">14-day free trial · Up to 30 voice-agent handled calls included</div><ProductPreview /></div></section>
      <section className="trusted"><div className="shell">Built for businesses that can’t afford to miss calls.<div className="empty-logos" aria-label="Space reserved for customer logos">{Array.from({ length: 5 }, (_, i) => <span key={i} />)}</div></div></section>
      <section className="section"><div className="shell"><div className="section-head"><span className="eyebrow">The cost of silence</span><h2>Every missed call is lost revenue.</h2><p>Customer expectations do not pause when your team is busy. Portico makes every first response immediate.</p></div><div className="cards">{problems.map(([Icon, title, body]) => { const I = Icon as typeof PhoneCall; return <div className="card" key={title as string}><I className="icon" size={22} /><h3>{title as string}</h3><p>{body as string}</p></div>; })}</div></div></section>
      <section id="solution" className="section soft"><div className="shell"><div className="section-head"><span className="eyebrow">The Portico model</span><h2>Efficiency when it helps. Expertise when it matters.</h2><p>Portico is a hybrid call center—built to resolve the straightforward and elevate the important.</p></div><div className="flow">{["Customer calls", "Voice agent answers", "Can it solve it?", "Resolved", "Warm transfer", "Human support", "Customer helped"].map((item, i) => <div className="flow-item" key={item}>{i > 0 && <ArrowRight className="arrow" size={18} />}<div className="flow-step">{item}</div></div>)}</div></div></section>
      <section className="section"><div className="shell"><div className="section-head"><span className="eyebrow">Why hybrid wins</span><h2>The dependable layer your customer experience needs.</h2></div><div className="compare">{[["", "Traditional call center", "Voice-only", "Portico"], ["Availability", "Business hours", "24/7", "24/7"], ["Customer experience", "Variable", "Limited escalation", "Human when needed"], ["Complex requests", "Capable", "Limited", "Handled smoothly"], ["Response time", "Queue dependent", "Instant", "Instant"], ["Scalability", "Costly", "High", "High, with care"]].map((row, i) => <div className={`compare-row ${i === 0 ? "header" : ""}`} key={row[0]}>{row.map((item, j) => <div key={j}>{item}</div>)}</div>)}</div></div></section>
      <section className="section soft"><div className="shell"><div className="section-head"><span className="eyebrow">Built around the call</span><h2>Everything you need to deliver a better first response.</h2></div><div className="cards features">{features.map(([Icon, title]) => { const I = Icon as typeof PhoneCall; return <div className="card" key={title as string}><I className="icon" size={20} /><h3>{title as string}</h3><p>Designed to keep each conversation moving forward.</p></div>; })}</div></div></section>
      <section className="section"><div className="shell"><div className="section-head"><span className="eyebrow">Full visibility</span><h2>A clear view of every conversation.</h2><p>See call activity, appointments, transfers and the context behind every customer touchpoint.</p></div><div className="dash-preview"><ProductPreview /></div></div></section>
      <section id="industries" className="section soft"><div className="shell"><div className="section-head"><span className="eyebrow">Made for real operations</span><h2>Reliable calls across every kind of service business.</h2></div><div className="cards industry">{industries.map(([Icon, title]) => { const I = Icon as typeof PhoneCall; return <div className="card" key={title as string}><I className="icon" size={19} /><h3>{title as string}</h3></div>; })}</div></div></section>
      <section id="pricing" className="section"><div className="shell"><div className="section-head"><span className="eyebrow">Straightforward start</span><h2>Choose the way you want to begin.</h2></div><div className="pricing"><div className="plan"><span className="eyebrow">Self-serve</span><h3>For growing businesses.</h3><p>Start answering more calls today.</p><ul><li>14-day free trial</li><li>Up to 30 voice-agent handled calls</li><li>No setup fee</li><li>Cancel anytime</li></ul><button className="button primary" onClick={() => open("trial")}>Start Free Trial</button></div><div id="enterprise" className="plan featured"><span className="eyebrow enterprise-label">Enterprise</span><h3>Built around your operation.</h3><p>Custom workflows for teams where every conversation counts.</p><ul><li>Custom voice workflows</li><li>CRM integrations</li><li>Dedicated onboarding</li><li>Ongoing support</li><li>Setup fee</li></ul><button className="button light" onClick={() => open("demo")}>Book Demo</button></div></div></div></section>
      <section className="section soft"><div className="shell"><div className="section-head"><span className="eyebrow">Questions, answered</span><h2>What to expect from Portico.</h2></div><div className="faq">{faq.map(([question, answer]) => <details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div></div></section>
      <section className="cta"><div className="shell"><h2>Never Miss Another<br />Customer Call.</h2><p>Voice agents answer instantly. Humans handle what matters.</p><div className="hero-actions"><button className="button primary" onClick={() => open("trial")}>Start Free Trial</button><button className="button dark-outline" onClick={() => open("demo")}>Book Enterprise Demo</button></div></div></section>
    </main><footer className="footer"><div className="shell footer-inner"><a className="wordmark" href="#top">PORTICO</a><div className="footer-links"><a href="#solution">Solutions</a><a href="#pricing">Pricing</a><a href="#enterprise">Enterprise</a><a href="mailto:hello@portico.intelligence">Email us</a></div></div></footer>{modal && <ContactModal mode={modal} onClose={() => setModal(null)} />}</>;
}
